# Generated by Django 6.0 on 2026-01-05 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='metodo',
            field=models.CharField(choices=[('V', 'Pix / Débito'), ('C', 'Cartão de Crédito')], default='V', max_length=1, verbose_name='Método'),
        ),
    ]
