# Generated by Django 6.0 on 2026-01-09 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transacao_metodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='id_parcelamento',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transacao',
            name='parcela_atual',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='transacao',
            name='parcela_total',
            field=models.IntegerField(default=1),
        ),
    ]
