# Generated by Django 6.0 on 2026-01-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_transacao_id_parcelamento_transacao_parcela_atual_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome']},
        ),
        migrations.AddField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('D', 'Gastos / Saídas'), ('R', 'Renda / Entradas')], default='D', max_length=1),
        ),
    ]
