# Generated by Django 6.0 on 2026-01-13 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_categoria_options_categoria_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tipo',
            field=models.CharField(choices=[('D', 'Despesa'), ('R', 'Renda')], default='D', max_length=1),
        ),
    ]
