# Generated by Django 6.0 on 2026-01-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_categoria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='ignorar_grafico',
            field=models.BooleanField(default=False, verbose_name='Ocultar nos Gráficos'),
        ),
    ]
